git: fix prefix use and aarch64 build error
i got the error:
undefined reference to __aarch64_swp4_acq
linking to libcurl.a

this and other similarly named symbols apparently require that
libgcc be statically linked (only when static linking is used?).