libtorrent: disable usage of nonportable atomics
breaks on x86 with
undefined reference to `__sync_add_and_fetch_8'
undefined reference to `__sync_fetch_and_and_8'

https://github.com/rakshasa/rtorrent/issues/156