add preliminary support LTS kernel 5.15 as "kernel515"
caveat emptor: the kernel builds, but was not boot-tested, so it's
possible some things are broken.

objtool strikes again:
In file included from /usr/include/linux/byteorder/little_endian.h:13:0,
                 from /usr/include/asm/byteorder.h:5,
                 from /src/build/kernel515/linux-5.15/tools/arch/x86/include/asm/insn.h:10,
                 from arch/x86/decode.c:10:
/usr/include/linux/swab.h:161:8: error: unknown type name '__always_inline'
 static __always_inline __u16 __swab16p(const __u16 *p)
        ^~~~~~~~~~~~~~~
... <list goes on> ...

objtool has a copy of some uapi headers in tools/arch/x86/include/asm/,
in order to prevent inclusion of incompatible host headers, but the list
is no longer complete and includes byteorder.h and swab.h from the host.
we fix it by copying those 2 headers into that directory.
see ab721aad793d8d21a8a351b7bd41e8d8c4fe9fdc for more details on objtool.

additionally the kbuild build system no longer supports "hostprogs-y", as
used by linux-timeconst-nobc-kbuild5.patch. instead, hostprogs-always-y
has to be used, which is recognized by kernel 5.10's kbuild too, but not
5.4's. so we now special-case 5.4 to use the old version of the patch
and use a fixed version for newer kernels.