Revert "libevent: bump to 2.1.8"
This reverts commit 5cd95e0d0cd00267130164f391f8fceded0056e1.

The update breaks firefox. apparently the 2 versions are not entirely
compatible.

In file included from /src/build/firefox/firefox-45.7.0esr/firefox-build-dir/ipc/chromium/Unified_cpp_ipc_chromium0.cpp:128:0:
/src/build/firefox/firefox-45.7.0esr/ipc/chromium/src/base/message_pump_libevent.cc:24:19: error: '_EVENT_SIZEOF_LONG' was not declared in this scope
     static_assert(_EVENT_SIZEOF_##TYPE == sizeof(type), \
                   ^
/src/build/firefox/firefox-45.7.0esr/ipc/chromium/src/base/message_pump_libevent.cc:27:1: note: in expansion of macro 'CHECK_EVENT_SIZEOF'
 CHECK_EVENT_SIZEOF(LONG,      long);
 ^~~~~~~~~~~~~~~~~~
/src/build/firefox/firefox-45.7.0esr/ipc/chromium/src/base/message_pump_libevent.cc:24:19: error: '_EVENT_SIZEOF_LONG_LONG' was not declared in this scope
     static_assert(_EVENT_SIZEOF_##TYPE == sizeof(type), \
                   ^
/src/build/firefox/firefox-45.7.0esr/ipc/chromium/src/base/message_pump_libevent.cc:28:1: note: in expansion of macro 'CHECK_EVENT_SIZEOF'
 CHECK_EVENT_SIZEOF(LONG_LONG, long long);
 ^~~~~~~~~~~~~~~~~~
/src/build/firefox/firefox-45.7.0esr/ipc/chromium/src/base/message_pump_libevent.cc:24:19: error: '_EVENT_SIZEOF_PTHREAD_T' was not declared in this scope
     static_assert(_EVENT_SIZEOF_##TYPE == sizeof(type), \