gcc3: fix new build error with host GCC 15
GCC 15 defaults to -std=gnu23 which breaks previously valid function
signatures, in this specific case the error was:

getpwd.c:41:14: error: conflicting types for ‘getwd’; have ‘char *(void)’
   41 | extern char *getwd ();
      |              ^~~~~
In file included from getpwd.c:30:
/usr/include/unistd.h:545:14: note: previous declaration of ‘getwd’ with type ‘char *(char *)’
  545 | extern char *getwd (char *__buf)
      |              ^~~~~