sdl2: disable -Werror (breaks powerpc)
SDL2-2.0.5/src/video/SDL_blit_N.c: In function 'calc_swizzle32':
SDL2-2.0.5/src/video/SDL_blit_N.c:127:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]